replicaCount: 1

image:
  repository: ghcr.io/devops-master-projects/booking-service
  pullPolicy: Always
  tag: "sha-5ebf8bd"

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: "booking-service"

service:
  type: ClusterIP
  port: 8086
  targetPort: 8086

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /api/bookings
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

springboot:
  profiles: "prod"

# Database configuration
database:
  host: "booking-postgres-service"
  port: "5432"
  name: "booking"
  username: "admin"
  password: "password"

# Keycloak configuration
keycloak:
  serverUrl: "http://keycloak-service:8080"
  realm: "IdentityRealm"

# Kafka configuration
kafka:
  bootstrapServers: "kafka-service:9092"

# Other services
services:
  accommodationUrl: "http://accommodation-service:8085"

env:
  - name: SERVER_PORT
    value: "8086"
  - name: SPRING_JPA_HIBERNATE_DDL_AUTO
    value: "update"
  - name: SPRING_JPA_OPEN_IN_VIEW
    value: "false"
  - name: SPRING_JPA_SHOW_SQL
    value: "false"
  - name: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
    value: "0"

livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: 8086
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: 8086
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80