replicaCount: 1

image:
  repository: ghcr.io/devops-master-projects/identity-service
  pullPolicy: Always
  tag: "sha-f55f355"

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: "identity-service"

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /api/identity
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

springboot:
  profiles: "prod"
  
# Database configuration - koristi postgres-service iz K8s
database:
  host: "postgres-service"
  port: "5432"
  name: "identity"
  username: "admin"
  password: "password"

# Keycloak configuration - VAŽNO: ažurirano
keycloak:
  serverUrl: "http://keycloak-service:8080"
  realm: "IdentityRealm"
  clientId: "identity-service"
  clientSecret: "mM0Y1phi6QcmDJJRemR6k4NXVgiV1E2l"

# Kafka configuration - ostavite ako nemate Kafka
kafka:
  bootstrapServers: "kafka-service:9092"
  groupId: "identity-service-group"

# Additional environment variables
env:
  - name: SERVER_PORT
    value: "8082"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "health,info,prometheus"
  - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
    value: "true"
  - name: SPRING_JPA_HIBERNATE_DDL_AUTO
    value: "update"
  - name: SPRING_JPA_OPEN_IN_VIEW
    value: "false"
  - name: SPRING_JPA_SHOW_SQL
    value: "false"
  - name: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
    value: "0"
  - name: NOTIFICATION_SERVICE_URL
    value: "http://notification-service:8088"

livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/liveness
    port: 8082
  initialDelaySeconds: 40
  periodSeconds: 30
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/readiness
    port: 8082
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80