apiVersion: v1
kind: Secret
metadata:
  name: {{ include "booking-service.fullname" . }}-secret
  labels:
    {{- include "booking-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database credentials
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  
  # OAuth2 Resource Server - JWT
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "{{ .Values.keycloak.serverUrl }}/realms/{{ .Values.keycloak.realm }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "{{ .Values.keycloak.serverUrl }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/certs"
  
  # Kafka configuration
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: "org.springframework.kafka.support.serializer.JsonSerializer"
  
  # Accommodation service URL
  ACCOMMODATION_SERVICE_URL: {{ .Values.services.accommodationUrl | quote }}