apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kibana.name" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kibana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kibana.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5601
              protocol: TCP
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.elasticsearch.hosts | quote }}
            - name: XPACK_SECURITY_ENABLED
              value: {{ ternary "true" "false" .Values.security.enabled | quote }}
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: {{ if .Values.elasticsearch.sslVerify | default false | eq true }}"full"{{ else }}"none"{{ end }}
            - name: LOGGING_ROOT_LEVEL
              value: {{ .Values.logging.level | quote }}
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
