{{- if .Values.tempo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
  labels:
    app: tempo
spec:
  replicas: {{ .Values.tempo.replicas }}
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
      - name: tempo
        image: {{ .Values.tempo.image.repository }}:{{ .Values.tempo.image.tag }}
        args:
        - -config.file=/etc/tempo/tempo.yaml
        ports:
        - name: http
          containerPort: 3200
        - name: grpc
          containerPort: 4317
        - name: otlp-http
          containerPort: 4318
        volumeMounts:
        - name: config
          mountPath: /etc/tempo
        - name: storage
          mountPath: /tmp/tempo
        resources:
          {{- toYaml .Values.tempo.resources | nindent 10 }}
      volumes:
      - name: config
        configMap:
          name: tempo-config
      - name: storage
        {{- if .Values.tempo.persistence.enabled }}
        persistentVolumeClaim:
          claimName: tempo-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}