{{- if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
spec:
  replicas: {{ .Values.loki.replicas }}
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: {{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}
        args:
        - -config.file=/etc/loki/loki.yaml
        ports:
        - name: http
          containerPort: 3100
        - name: grpc
          containerPort: 9096
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /loki
        resources:
          {{- toYaml .Values.loki.resources | nindent 10 }}
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: storage
        {{- if .Values.loki.persistence.enabled }}
        persistentVolumeClaim:
          claimName: loki-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}