apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-app.fullname" . }}
  labels:
    {{- include "frontend-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frontend-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "frontend-app.fullname" . }}-nginx-config