apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend-app.fullname" . }}-nginx-config
  labels:
    {{- include "frontend-app.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;

      # ----------------------------
      # FIX za dupli /api po servisima
      # ----------------------------

      # Identity: /api/identity/api/... -> /api/...
      location ~ ^/api/identity/api/(.*)$ {
        rewrite ^/api/identity/api/(.*)$ /api/$1 break;
        proxy_pass http://identity-service:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
      # Normalan prolaz
      location /api/identity/ {
        proxy_pass http://identity-service:8082/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Accommodations: /api/accommodations/api/... -> /api/...
      location ~ ^/api/accommodations/api/(.*)$ {
        rewrite ^/api/accommodations/api/(.*)$ /api/$1 break;
        proxy_pass http://accommodation-service:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
      # Normalan prolaz
      location /api/accommodations/ {
        proxy_pass http://accommodation-service:8085/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Bookings: /api/bookings/api/... -> /api/...
      location ~ ^/api/bookings/api/(.*)$ {
        rewrite ^/api/bookings/api/(.*)$ /api/$1 break;
        proxy_pass http://booking-service:8086;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
      # Normalan prolaz
      location /api/bookings/ {
        proxy_pass http://booking-service:8086/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Search: /api/search/api/... -> /api/...
      location ~ ^/api/search/api/(.*)$ {
        rewrite ^/api/search/api/(.*)$ /api/$1 break;
        proxy_pass http://search-service:8087;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
      # Normalan prolaz
      location /api/search/ {
        proxy_pass http://search-service:8087/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Notifications (REST): /api/notifications/api/... -> /api/...
      location ~ ^/api/notifications/api/(.*)$ {
        rewrite ^/api/notifications/api/(.*)$ /api/$1 break;
        proxy_pass http://notification-service:8088;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
      # Normalan prolaz
      location /api/notifications/ {
        proxy_pass http://notification-service:8088/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # WebSocket
      location /ws {
        proxy_pass http://notification-service:8088/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
      }

      # ==============================================
      # REVIEW SERVICE RULES - MORAJU BITI PRE SPA FALLBACK-A
      # ==============================================

      # Fix: /hosts/{hostId}/reviews/{reviewId}/undefined/api/reviews/hosts/{reviewId} (GET/EDIT pojedinacne)
      location ~ ^/hosts/([^/]+)/reviews/([^/]+)/undefined/api/reviews/hosts/([^/]+)$ {
        rewrite ^/hosts/([^/]+)/reviews/([^/]+)/undefined/api/reviews/hosts/([^/]+)$ /api/reviews/hosts/$3 break;
        proxy_pass http://review-service:8089;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Fix: /hosts/undefined/api/reviews/hosts/{reviewId} (DELETE pojedinacne - BEZ /reviews na kraju!)
      location ~ ^/hosts/undefined/api/reviews/hosts/([^/]+)$ {
        rewrite ^/hosts/undefined/api/reviews/hosts/([^/]+)$ /api/reviews/hosts/$1 break;
        proxy_pass http://review-service:8089;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Fix: /hosts/undefined/api/reviews/hosts/{id}/reviews (lista SA /reviews na kraju)
      location ~ ^/hosts/undefined/api/reviews/hosts/([^/]+)/reviews(.*)$ {
        rewrite ^/hosts/undefined/api/reviews/hosts/([^/]+)/reviews(.*)$ /api/reviews/hosts/$1/reviews$2 break;
        proxy_pass http://review-service:8089;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Fix: /hosts/{id}/reviews/undefined/api/reviews/hosts (POST nova review)
      location ~ ^/hosts/([^/]+)/reviews/undefined/api/reviews/hosts(.*)$ {
        rewrite ^/hosts/([^/]+)/reviews/undefined/api/reviews/hosts(.*)$ /api/reviews/hosts$2 break;
        proxy_pass http://review-service:8089;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Fix: /accommodations/undefined/api/reviews/accommodations/{id}
      location ~ ^/accommodations/undefined/api/reviews/accommodations/([^/]+)(.*)$ {
        rewrite ^/accommodations/undefined/api/reviews/accommodations/([^/]+)(.*)$ /api/reviews/accommodations/$1$2 break;
        proxy_pass http://review-service:8089;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Fix: /accommodations/{id}/reviews/.../api/reviews/...
      location ~ ^/accommodations/[^/]+/reviews/.*/api/reviews/(.*)$ {
        rewrite ^/accommodations/[^/]+/reviews/.*/api/reviews/(.*)$ /api/reviews/$1 break;
        proxy_pass http://review-service:8089;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Fix: /api/reviews/hosts/undefined/...
      location ~ ^/api/reviews/hosts/undefined/(.*)$ {
        rewrite ^/api/reviews/hosts/undefined/(.*)$ /api/reviews/hosts/4e9a3623-4424-4bba-b7b7-354fa6f753b1/$1 break;
        proxy_pass http://review-service:8089;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Fix: /api/reviews/accommodations/undefined/...
      location ~ ^/api/reviews/accommodations/undefined/(.*)$ {
        rewrite ^/api/reviews/accommodations/undefined/(.*)$ /api/reviews/accommodations/1cd50aba-6c8e-44ab-b5f6-0ff6a0cae178/$1 break;
        proxy_pass http://review-service:8089;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Fix: /api/accommodations/api/reviews/...
      location ~ ^/api/accommodations/api/reviews/(.*)$ {
        rewrite ^/api/accommodations/api/reviews/(.*)$ /api/reviews/$1 break;
        proxy_pass http://review-service:8089;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Normal review service pass-through
      location ^~ /api/reviews/ {
        proxy_pass http://review-service:8089;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # SPA fallback - MORA BITI NA KRAJU!
      location / {
        try_files $uri /index.html;
      }
    }