apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend-app.fullname" . }}-nginx-config
  labels:
    {{- include "frontend-app.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;

      location /api/identity/ {
        proxy_pass http://identity-service:8082/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      location /api/accommodations/ {
        proxy_pass http://accommodation-service:8085/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /api/bookings/ {
        proxy_pass http://booking-service:8086/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /api/search/ {
        proxy_pass http://search-service:8087/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /api/notifications/ {
        proxy_pass http://notification-service:8088/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /ws {
        proxy_pass http://notification-service:8088/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
      }

      location / {
        try_files $uri /index.html;
      }
    }