apiVersion: v1
kind: Service
metadata:
  name: accommodation-postgres-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5432
  selector:
    app: accommodation-postgres
