apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |
    CREATE USER keycloakuser WITH PASSWORD 'keycloakpassword';
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloakuser;
    ALTER DATABASE keycloak OWNER TO keycloakuser;