replicaCount: 1

image:
  repository: ghcr.io/devops-master-projects/search-service
  pullPolicy: Always
  tag: "sha-d958152"

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: "search-service"

service:
  type: ClusterIP
  port: 8087
  targetPort: 8087

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /api/search
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

springboot:
  profiles: "prod"

# Elasticsearch configuration
elasticsearch:
  uris: "http://elasticsearch-service:9200"

# Keycloak configuration
keycloak:
  serverUrl: "http://keycloak-service:8080"
  realm: "IdentityRealm"

# Kafka configuration
kafka:
  bootstrapServers: "kafka-service:9092"
  consumerGroupId: "search-service"
  autoOffsetReset: "earliest"
  consumer:
    keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    valueDeserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
    trustedPackages: "org.example.search.dto"

# CORS configuration
cors:
  allowedOrigins: "http://localhost:5173"

# Observability configuration
observability:
  tempoOtlp: "http://tempo:4318/v1/traces"
  lokiUrl: "http://loki:3100"

# Environment variables
env:
  - name: SERVER_PORT
    value: "8087"
  
  # === OBSERVABILITY - DODATO ===
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "health,info,prometheus,metrics"
  - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
    value: "always"
  - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
    value: "true"
  - name: MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED
    value: "true"
  - name: MANAGEMENT_HEALTH_READINESSSTATE_ENABLED
    value: "true"
  - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
    value: "true"
  
  # Metrics tags
  - name: MANAGEMENT_METRICS_TAGS_APPLICATION
    value: "search-service"
  - name: MANAGEMENT_METRICS_TAGS_ENVIRONMENT
    value: "kubernetes"
  
  # Tracing
  - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
    value: "1.0"
  - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
    value: "http://tempo:4318/v1/traces"
  
  # Loki
  - name: LOKI_URL
    value: "http://loki:3100"
  
  # Info endpoint
  - name: MANAGEMENT_INFO_ENV_ENABLED
    value: "true"
  
  # Logging levels
  - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA
    value: "INFO"
  - name: LOGGING_LEVEL_ORG_APACHE_KAFKA
    value: "INFO"
  - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
    value: "INFO"
  - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
    value: "INFO"

# Health probes
livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/liveness
    port: 8087
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/readiness
    port: 8087
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80